name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  push:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake graph
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          output: dist/snake.svg

      # Step 3: Commit and push the updated snake graph
      - name: Commit and Push Snake Graph
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/snake.svg
          git commit -m "Updated Snake Graph"
          git push
